services:
  gorget_api:
    build:
      context: ..
      dockerfile: gorget_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config/scanners.yml:/home/user/app/config/scanners.yml
